/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectIdIndexRouteImport } from './routes/subject/$id/index'
import { Route as SubjectIdMistakesRouteImport } from './routes/subject/$id/mistakes'
import { Route as SubjectIdGuideRouteImport } from './routes/subject/$id/guide'
import { Route as SubjectIdExamRouteImport } from './routes/subject/$id/exam'
import { Route as SubjectIdPracticeSequentialRouteImport } from './routes/subject/$id/practice/sequential'
import { Route as SubjectIdPracticeRandomRouteImport } from './routes/subject/$id/practice/random'
import { Route as SubjectIdPracticeChapterChapterIdRouteImport } from './routes/subject/$id/practice/chapter/$chapterId'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectIdIndexRoute = SubjectIdIndexRouteImport.update({
  id: '/subject/$id/',
  path: '/subject/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectIdMistakesRoute = SubjectIdMistakesRouteImport.update({
  id: '/subject/$id/mistakes',
  path: '/subject/$id/mistakes',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectIdGuideRoute = SubjectIdGuideRouteImport.update({
  id: '/subject/$id/guide',
  path: '/subject/$id/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectIdExamRoute = SubjectIdExamRouteImport.update({
  id: '/subject/$id/exam',
  path: '/subject/$id/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectIdPracticeSequentialRoute =
  SubjectIdPracticeSequentialRouteImport.update({
    id: '/subject/$id/practice/sequential',
    path: '/subject/$id/practice/sequential',
    getParentRoute: () => rootRouteImport,
  } as any)
const SubjectIdPracticeRandomRoute = SubjectIdPracticeRandomRouteImport.update({
  id: '/subject/$id/practice/random',
  path: '/subject/$id/practice/random',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectIdPracticeChapterChapterIdRoute =
  SubjectIdPracticeChapterChapterIdRouteImport.update({
    id: '/subject/$id/practice/chapter/$chapterId',
    path: '/subject/$id/practice/chapter/$chapterId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stats': typeof StatsRoute
  '/subject/$id/exam': typeof SubjectIdExamRoute
  '/subject/$id/guide': typeof SubjectIdGuideRoute
  '/subject/$id/mistakes': typeof SubjectIdMistakesRoute
  '/subject/$id/': typeof SubjectIdIndexRoute
  '/subject/$id/practice/random': typeof SubjectIdPracticeRandomRoute
  '/subject/$id/practice/sequential': typeof SubjectIdPracticeSequentialRoute
  '/subject/$id/practice/chapter/$chapterId': typeof SubjectIdPracticeChapterChapterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stats': typeof StatsRoute
  '/subject/$id/exam': typeof SubjectIdExamRoute
  '/subject/$id/guide': typeof SubjectIdGuideRoute
  '/subject/$id/mistakes': typeof SubjectIdMistakesRoute
  '/subject/$id': typeof SubjectIdIndexRoute
  '/subject/$id/practice/random': typeof SubjectIdPracticeRandomRoute
  '/subject/$id/practice/sequential': typeof SubjectIdPracticeSequentialRoute
  '/subject/$id/practice/chapter/$chapterId': typeof SubjectIdPracticeChapterChapterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/stats': typeof StatsRoute
  '/subject/$id/exam': typeof SubjectIdExamRoute
  '/subject/$id/guide': typeof SubjectIdGuideRoute
  '/subject/$id/mistakes': typeof SubjectIdMistakesRoute
  '/subject/$id/': typeof SubjectIdIndexRoute
  '/subject/$id/practice/random': typeof SubjectIdPracticeRandomRoute
  '/subject/$id/practice/sequential': typeof SubjectIdPracticeSequentialRoute
  '/subject/$id/practice/chapter/$chapterId': typeof SubjectIdPracticeChapterChapterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/stats'
    | '/subject/$id/exam'
    | '/subject/$id/guide'
    | '/subject/$id/mistakes'
    | '/subject/$id/'
    | '/subject/$id/practice/random'
    | '/subject/$id/practice/sequential'
    | '/subject/$id/practice/chapter/$chapterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/stats'
    | '/subject/$id/exam'
    | '/subject/$id/guide'
    | '/subject/$id/mistakes'
    | '/subject/$id'
    | '/subject/$id/practice/random'
    | '/subject/$id/practice/sequential'
    | '/subject/$id/practice/chapter/$chapterId'
  id:
    | '__root__'
    | '/'
    | '/stats'
    | '/subject/$id/exam'
    | '/subject/$id/guide'
    | '/subject/$id/mistakes'
    | '/subject/$id/'
    | '/subject/$id/practice/random'
    | '/subject/$id/practice/sequential'
    | '/subject/$id/practice/chapter/$chapterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StatsRoute: typeof StatsRoute
  SubjectIdExamRoute: typeof SubjectIdExamRoute
  SubjectIdGuideRoute: typeof SubjectIdGuideRoute
  SubjectIdMistakesRoute: typeof SubjectIdMistakesRoute
  SubjectIdIndexRoute: typeof SubjectIdIndexRoute
  SubjectIdPracticeRandomRoute: typeof SubjectIdPracticeRandomRoute
  SubjectIdPracticeSequentialRoute: typeof SubjectIdPracticeSequentialRoute
  SubjectIdPracticeChapterChapterIdRoute: typeof SubjectIdPracticeChapterChapterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subject/$id/': {
      id: '/subject/$id/'
      path: '/subject/$id'
      fullPath: '/subject/$id/'
      preLoaderRoute: typeof SubjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subject/$id/mistakes': {
      id: '/subject/$id/mistakes'
      path: '/subject/$id/mistakes'
      fullPath: '/subject/$id/mistakes'
      preLoaderRoute: typeof SubjectIdMistakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subject/$id/guide': {
      id: '/subject/$id/guide'
      path: '/subject/$id/guide'
      fullPath: '/subject/$id/guide'
      preLoaderRoute: typeof SubjectIdGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subject/$id/exam': {
      id: '/subject/$id/exam'
      path: '/subject/$id/exam'
      fullPath: '/subject/$id/exam'
      preLoaderRoute: typeof SubjectIdExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subject/$id/practice/sequential': {
      id: '/subject/$id/practice/sequential'
      path: '/subject/$id/practice/sequential'
      fullPath: '/subject/$id/practice/sequential'
      preLoaderRoute: typeof SubjectIdPracticeSequentialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subject/$id/practice/random': {
      id: '/subject/$id/practice/random'
      path: '/subject/$id/practice/random'
      fullPath: '/subject/$id/practice/random'
      preLoaderRoute: typeof SubjectIdPracticeRandomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subject/$id/practice/chapter/$chapterId': {
      id: '/subject/$id/practice/chapter/$chapterId'
      path: '/subject/$id/practice/chapter/$chapterId'
      fullPath: '/subject/$id/practice/chapter/$chapterId'
      preLoaderRoute: typeof SubjectIdPracticeChapterChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StatsRoute: StatsRoute,
  SubjectIdExamRoute: SubjectIdExamRoute,
  SubjectIdGuideRoute: SubjectIdGuideRoute,
  SubjectIdMistakesRoute: SubjectIdMistakesRoute,
  SubjectIdIndexRoute: SubjectIdIndexRoute,
  SubjectIdPracticeRandomRoute: SubjectIdPracticeRandomRoute,
  SubjectIdPracticeSequentialRoute: SubjectIdPracticeSequentialRoute,
  SubjectIdPracticeChapterChapterIdRoute:
    SubjectIdPracticeChapterChapterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
